const NODE_INSTANCE_PATH_ARGUMENT_INDEX = 0;
const SCRIPT_PATH_ARGUMENT_INDEX = 1;
const SCRIPT_ARGUMENTS_START_INDEX = 2;

module.exports = {
  NODE_INSTANCE_PATH_ARGUMENT_INDEX,
  SCRIPT_PATH_ARGUMENT_INDEX,
  SCRIPT_ARGUMENTS_START_INDEX,
};
